# -*- coding: utf-8 -*-

lista_qualivida = [
    'MEDICO PAI QUALIVIDA',
    'MEDICO OBESIDADE QUALIVIDA',
    'CARDIOLOGIA QUALIVIDA',
    'MÉDICO DA COLUNA QUALIVIDA',
    'NUTRICAO QUALIVIDA',
    'CLINICO GERAL QUALIVIDA',
    'GERONTOLOGIA QUALIVIDA',
    'ENFERMAGEM OBESIDADE QUALIVIDA',
    'FISIOTERAPIA QUALIVIDA',
    'PSICOLOGIA QUALIVIDA',
]
